In [2]:
import numpy as np
a=np.array([0,1,2])
print(type(a))
print(a.shape)
print(a[0])
print(a[1])
print(a[2])


<class 'numpy.ndarray'>
(3,)
0
1
2


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [5]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
b=np.ones((4,6))
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [9]:
c=np.full((4,2),24)
print(c)

[[24 24]
 [24 24]
 [24 24]
 [24 24]]


In [10]:
d=np.random.random((4,4))
print(d)


e=np.random.random(10)
print(e)

[[0.92471717 0.30860434 0.35070216 0.660973  ]
 [0.27482833 0.10202087 0.09380196 0.85611803]
 [0.26648391 0.05081406 0.06277549 0.22567249]
 [0.59209459 0.44617915 0.31439271 0.66180342]]
[0.51307765 0.14136269 0.29995168 0.37510694 0.57561128 0.05500232
 0.64989953 0.91874742 0.850625   0.77047726]


In [12]:
f=np.eye(6)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


Data structures


array can only store homogeneous elements  [2,3,4]
list stores heterogeneous elements  [2,'r','sai']
tuple also stores heterogeneous elements but this is immutable whereas lists are mutable (3, 'saisri', 5.0)
dictionary stores key value pairs



In [15]:
#convert list to array
l=[1,'d',8.0]
g=np.array(l)
print(g)
print(type(g))

['1' 'd' '8.0']
<class 'numpy.ndarray'>


In [21]:
#arrange function
a=np.arange(10)
print(a)

#increment by given value
b=np.arange(2,10,2)
print(b)

#can jump by decreasing, float range
c=np.arange(10,2,-2)
print(c)

d=np.arange(3,10,0.25)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]
[10  8  6  4]
[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25
 6.5  6.75 7.   7.25 7.5  7.75 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [23]:
#mix of lists and tuples
h=np.array([[1,2,3],('e',0.3,'sdfsdf'),(0,0,0)])
print(h)

[['1' '2' '3']
 ['e' '0.3' 'sdfsdf']
 ['0' '0' '0']]


In [29]:
#np.arrange for float values
a=np.arange(1,10,0.5)
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [28]:
#linspace()

a=np.linspace(1,10,5)
print(a)
print(a.dtype)

[ 1.    3.25  5.5   7.75 10.  ]
float64


Array indexing


In [36]:
arr=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])
print(arr)

#slicing
a=arr[:3,::2]
b=arr[:2,:2]
print(a)
print(b)



[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
[[1 3]
 [4 6]
 [7 9]]
[[1 2]
 [4 5]]


In [39]:
# accsess array elements with rows and columns indices
arr=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])

temp=arr[[1,2],[1,1]]# first list contains all row indices and next tupe contains all columns indices here (1,1),(2,1)
print(temp)


[5 8]


In [41]:
#boolean array indexing
arr=np.array([[1,-2,3,-10],[4,5,-6,11],[7,8,9,-12]])

temp=arr[arr>=8]
print(temp)

[11  8  9]


In [44]:
#adding 1 to every elements
arr=np.array([[1,-2,3,-10],[4,5,-6,11],[7,8,9,-12]])
arr=arr+1
print(arr)

#can also perform sub,mul,div,squaring,modify
arr=arr*5
print(arr)


[[  2  -1   4  -9]
 [  5   6  -5  12]
 [  8   9  10 -11]]
[[ 10  -5  20 -45]
 [ 25  30 -25  60]
 [ 40  45  50 -55]]


In [43]:
#transpose matrix array
arr=np.array([[1,-2,3,-10],[4,5,-6,11],[7,8,9,-12]])
print(arr.T)


[[  1   4   7]
 [ -2   5   8]
 [  3  -6   9]
 [-10  11 -12]]


In [49]:
#maximum element of array
arr=np.array([[1,-2,3,-10],[4,15,-6,11],[7,8,9,-12]])
print(arr.max())
#minimum
print(arr.min())
#specify row wise
print(arr.min(axis=1))
#specify column wise
print(arr.max(axis=0))


15
-12
[-10  -6 -12]
[ 7 15  9 11]


In [51]:
#array sum
arr=np.array([[1,-2,3,-10],[4,15,-6,11],[7,8,9,-12]])
print(arr.sum())
#cumsum()
print(arr.cumsum())
#column wise
print(arr.cumsum(axis=0))
#row wise
print(arr.cumsum(axis=1))
#

28
[ 1 -1  2 -8 -4 11  5 16 23 31 40 28]
[[  1  -2   3 -10]
 [  5  13  -3   1]
 [ 12  21   6 -11]]
[[ 1 -1  2 -8]
 [ 4 19 13 24]
 [ 7 15 24 12]]
